### PR TITLE
Adding ATR MCDU

### PR DESCRIPTION
**Pull request by bevinet**

### CODE REVIEW

**Comment by bevinet** [comment]
Adding ATR MCDU

**Comment by cdrage** [comment]
@Crunchmeister1 are we able to get this merged in?

**Comment by cdrage** [comment]
ping @rob2791

**Comment by bevinet** [comment]
Sorry am unable to do this now as my PC failed and no longer use Air manager

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
